# Generated by Django 5.0.2 on 2024-09-02 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo_ir', models.CharField(max_length=20)),
                ('temperatura', models.CharField(max_length=6)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ServerMQTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=255)),
                ('nivel', models.CharField(choices=[('Professor', 'Professor'), ('Coordenação de turma', 'Coordenação de turma')], default=('Coordenação de turma', 'Coordenação de turma'), max_length=30)),
                ('img_url', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('temperatura', models.CharField(max_length=6)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arCondicionado.dispositivos')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='serverMQTT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arCondicionado.servermqtt'),
        ),
    ]
