# Generated by Django 5.0.2 on 2024-09-03 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo_Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ArCondicionado', 'ArCondicionado'), ('Projetor', 'Projetor'), ('Televisão', 'Televisão')], max_length=255)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('codigo_IR', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServerMQTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=255)),
                ('nivel', models.CharField(choices=[('Professor', 'Professor'), ('Coordenação de turma', 'Coordenação de turma')], default=('Coordenação de turma', 'Coordenação de turma'), max_length=30)),
                ('img_url', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('modelo_Dispositivos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arCondicionado.modelo_dispositivos')),
            ],
        ),
        migrations.CreateModel(
            name='Modulo_IF_Smart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('temperatura', models.CharField(max_length=6)),
                ('dispositivo', models.ManyToManyField(to='arCondicionado.dispositivos')),
                ('serverMQTT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arCondicionado.servermqtt')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('local', models.CharField(choices=[('Bloco A', 'Bloca A'), ('Bloco B', 'Bloca B'), ('Bloco C', 'Bloca C'), ('Bloco Administrativo', 'Bloca Administrativo')], max_length=255)),
                ('temperatura', models.CharField(max_length=6)),
                ('modulo_IF_Smart', models.ManyToManyField(to='arCondicionado.modulo_if_smart')),
            ],
        ),
    ]
