# Generated by Django 5.0.2 on 2024-10-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arCondicionado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='login',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
