from .dispositivos_views import DispositivoControleTemperatura,GetDispositivos,DispositivoControleEstado,DispositivoDetailAPI
from .usuario_views import UsuárioViews,UsuárioNívelAcesso,UsuárioDetalhes