version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mqtt
      - redis
    env_file:
      - .env
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: smartif@root
      MYSQL_DATABASE: smartif
      MYSQL_USER: ifpb
      MYSQL_PASSWORD: smartif@24
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt_broker
    volumes:
      - ./mosquitto:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    ports:
      - "1883:1883"
    networks:
      - app_network
  
  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

volumes:
  mysql_data:
  mosquitto_data:
  mosquitto_logs:

