# Generated by Django 5.0.2 on 2024-11-01 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulosSmart', '0002_alter_comando_options_alter_modulo_smart_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comando', models.CharField(max_length=100)),
                ('usuario', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Log',
            },
        ),
    ]
