# Generated by Django 5.0.2 on 2024-11-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulosSmart', '0003_registrolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrolog',
            name='dispositivo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
