# Generated by Django 5.0.2 on 2024-11-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulosSmart', '0004_registrolog_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivos',
            name='max_temperatura',
            field=models.IntegerField(default=27),
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='min_temperatura',
            field=models.IntegerField(default=18),
        ),
    ]
