# Generated by Django 5.0.2 on 2024-11-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulosSmart', '0005_dispositivos_max_temperatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivos',
            name='tipo_id',
        ),
        migrations.AddField(
            model_name='dispositivos',
            name='nome',
            field=models.CharField(default='Ar Condicionado', max_length=100),
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
