# Generated by Django 5.0.2 on 2024-11-02 21:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulosSmart', '0006_remove_dispositivos_tipo_id_dispositivos_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDisposivito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='Ar Condicionado', max_length=100)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('min_temperatura', models.IntegerField(default=18)),
                ('max_temperatura', models.IntegerField(default=27)),
            ],
            options={
                'verbose_name': 'Modelo do Disposivito',
            },
        ),
        migrations.RemoveField(
            model_name='comando',
            name='dispositivo',
        ),
        migrations.RemoveField(
            model_name='dispositivos',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='dispositivos',
            name='max_temperatura',
        ),
        migrations.RemoveField(
            model_name='dispositivos',
            name='min_temperatura',
        ),
        migrations.RemoveField(
            model_name='dispositivos',
            name='nome',
        ),
        migrations.AddField(
            model_name='comando',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modulosSmart.modelodisposivito'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulosSmart.modelodisposivito'),
        ),
    ]
