# Generated by Django 5.0.2 on 2024-11-02 21:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulosSmart', '0007_modelodisposivito_remove_comando_dispositivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivos',
            options={'verbose_name': 'Disposivito'},
        ),
        migrations.AlterField(
            model_name='tipo_user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
