# Generated by Django 5.0.2 on 2024-11-10 19:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulosSmart', '0008_alter_dispositivos_options_alter_tipo_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comando',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulosSmart.modelodisposivito'),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulosSmart.modelodisposivito'),
        ),
        migrations.AlterField(
            model_name='dispositivos',
            name='sala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulosSmart.sala'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.ForeignKey(default='60d126a1c8d449968eac8cf3b53a1c55', on_delete=django.db.models.deletion.CASCADE, to='modulosSmart.tipo_user'),
        ),
        migrations.CreateModel(
            name='Registro_Cenários',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ação', models.BooleanField()),
                ('data', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('dispositivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulosSmart.dispositivos')),
            ],
            options={
                'verbose_name': 'Registro de Cenário',
            },
        ),
        migrations.DeleteModel(
            name='Registro_Uso',
        ),
    ]
