# Generated by Django 5.0.2 on 2024-11-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulosSmart', '0009_alter_comando_modelo_alter_dispositivos_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivos',
            name='atual_temperatura',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='registro_cenários',
            name='ação',
            field=models.BooleanField(choices=[(True, 'Ligar'), (False, 'Desligar')]),
        ),
        migrations.AlterField(
            model_name='registro_cenários',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ativado'), (False, 'Desativado')]),
        ),
    ]
