# Generated by Django 5.0.2 on 2024-12-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulosSmart', '0011_alter_usuario_nivel_remove_usuario_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Coordenação de turma', 'Coordenação de turma')], default='Professor', max_length=100),
        ),
    ]
