from .usuario_serializer import UsuarioSerializer,UsuarioDetalhesSerializer
from .setor_serializer import SetorsSerializer,SetorSerializer
from .sala_serializer import SalasSerializer,SalaSerializer
from .modelo_dispositivo_serializer import ModeloDisposivitoSerializer
from .dispositivo_serializer import DispositivosSerializer,DispositivoSerializer
from .cenario_serializer import RegistroCenáriosSerializer,RegistroCenárioSerializer